apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e2e-app
  template:
    metadata:
      labels:
        app: e2e-app
    spec:
      containers:
      - name: e2e-app
        image: saqlainkhan/pipeline:1.0.0-13
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080